name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: php:7.4-cli
    steps:
      - uses: actions/checkout@v2
      - name: Install zip
        run: apt update && apt install -y unzip
      - name: Install composer
        run: php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && php composer-setup.php --install-dir=/usr/bin --filename=composer && php -r "unlink('composer-setup.php');"
      - name: Install packages
        run: composer install
      - name: phpstan
        run: bash phpstan.sh
      - name: csfixer
        run: bash csfixer.sh --dry-run src tests
