name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install mongo-ext 1.6
      run: pecl install mongodb
    - name: Install packages
      run: composer install
    - name: phpstan
      run: bash phpstan.sh
